#+TITLE:Greetings from a leave of absence
#+DATE:<2022-05-10>
#+KEYWORDS: life
#+DESCRIPTION: For the past two months I've been on a leave of absence from work.

For the past two months I've been on a leave of absence from work, just to reorient myself a bit in the midst of chaos that our dear world is submerged in at the moment. I do feel truly blessed, as I could afford such a break from both social and corporate activities, being painfully aware that most people who'd deserve a similar pause won't be able to do so. So one can take this diatribe as a general criticism towards our society's relationship with work.

In my case, both the pandemic and the current geopolitical realities have made me realize how fragile and unsustainable my previous rhythm of working has been. I spent two-and-a-half years with my previous project, which is quite a lot, given that most of the things I have under my belt right now I learnt from this very opportunity. The core problem in no way was related to the domain, technologies used or the team. At the very core was my own personality, which led me to become increasingly insecure about my own work, which is something I'm slowly working through in cognitive therapy. I've always suffered from some perfectionism, compulsive behavior and getting stuck in loops of inane worry and rumination about minute details, but the isolation has made the issue much worse. I've made the switch from design into development relatively recently and I have a tendency to get very self-conscious about not having grown in an environment with other engineers and sharing some common experience. Instead, I grew up with dancers, actors, musicians and artists.

A big reason why I wanted to take some time off, was to reconnect with myself, with the things I hold most important in life and try to converge the experiences and and lessons I've learned from working as a developer in the past few years. For example, it's very hard to change and improve workflows, when you need to get things done. You just default to whatever you're used to on the first sign of frustration and unfamiliarity. In order for us to learn and improve our skills, there needs to happen a period of integration. Things take shape slowly and seep into the ways we work and express ourselves, little by little. If we never take the time to properly integrate new things into our thought-processes, we stagnate. The very tools that we use to understand the world around us can simply deprecate, and suddenly we're lost in a parallel existence, where nothing makes sense anymore.

So far, I feel like this absence from work has been a great success! I've managed to make huge new improvements in my game, solving some of the most glaring long-term architectural issues with it, which has crystallized the things I still need to implement before making a public release. I've improved the open-source components in my game and made some great gains in benchmarks. I've taken time to hone my Emacs configurations, making it into something I really feel at home with. I work smarter, not harder. I feel incredibly inspired by all the things around me, which is a very stark contrast to the dull drudgery of the first quarter. 

Programming feels still fun, which is the best takeaway from all this. Stress and overworking myself didn't manage to kill my passion, it's all about knowing when to stop, take a small step back and reflect on what you're doing wrong, instead of trying to power through, assuming there's something wrong with you as a fully functioning human being, when you are suddenly unable to perform inhuman feats.

Even the fact that I'm now finding time to update my blog is a good indicator that my professional confidence is healing. I'm already kinda looking forward to the next project when I ultimately return to work and I'm sure that this endless curiosity and willingness to solve intricate problems isn't going anywhere anytime soon.

Have a good day!
