#+TITLE:On bitterness
#+DATE: <2022-07-01>
#+KEYWORDS: life,philosophy
#+DESCRIPTION: I used to be an extremely bitter person. I also used to think I wasn't, which I think emphasizes the underlying issue with bitterness quite well.

I used to be an extremely bitter person. I also used to think I wasn't, which I think emphasizes the underlying issue with bitterness quite well. There's a saying, that bitterness is like drinking poison and expecting the other person to die. I don't know the origin for this aphorism and would expect it to be criminally misquoted all around the web, but I feel its core message stands. However, a bitter person will have a distorted understanding of the message. For them, this drinking of the poison is a noble sacrifice, a purifying act that makes them stronger, and separates them from everyone else. I too used to believe I was strong.

As humans, we tend to have all kinds of narratives and invented meanings about ourselves. The idea of gaining strength from resentment and anger is universal, and there are studies to suggest that the burst of adrenaline associated with emotional rage can elevate our physical prowess, but deep down, I find harboring hatred to be a fatal flaw and a weakness. Like anger, bitterness is a reaction to external events. We feel threatened or wronged by something or someone, thusly our well-being gets disturbed. For me, a person whose inner integrity is governed by outside forces, doesn't seem that strong, but instead spells the presence of fear, unstability and precariousness.

I've often been guilty of indulging in the narrative of being exceptionally smart and talented. I had an almost omnipotent view of myself, of being capable of anything, while at the same time wallowing in endless self-hatred and bitterness, blaming everyone else for my own shortcomings.

/How dare they keep me from achieving greatness!/ 

I think anyone who's been bullied before will recognize this kind of desire for retribution and justice, for the unfair treatment they've received. (Pseudo)-intellectualism was my refuge from the pain I was inflicted with. I doubled down on the narrative and descended into mindless nihilism and apathy, while at the same time believing I was above everyone. I was falsely enlightened by my own delusions of my intellect and rationality, while other people with convictions and morals were always weak and dull in my eyes. Yet I could not shake the feeling of helplessness or inferiority, no matter how I tried to reframe myself as part of some perceived elite and my pain and bitterness as an unending source for power and inspiration. 

My most severe shortcoming was that I was completely oblivious to the lies I was telling myself, about myself. My main concern was to convince myself of being greater than my deeds or wisdom (or lack thereof) could allow. As I was unable to recognize my hubris, whenever I felt vulnerable, I would just shift the criteria I used to judge myself, so I would always stay on the top. Now contrast this with what I wrote before, about unstability. Is it indeed strength, to have to change the rules whenever feeling threatened? 

Being smart or having natural talent means very little in the grand scheme of things. None of that translates to success unless tempered with wisdom and compassion. I am not here because I am smart, but because of countless hours of self-reflection, therapy and taking back my sense of self from the reactive bitterness and anger, that was slowly strangling me to death.
 
David Foster Wallace gave an interview in 2003, [[https://www.youtube.com/watch?v=iGLzWdT7vGc][of which an unedited version can be found on YouTube]] (seriously, watch it through, I really, really love this man), in which he said in passing: /"There's a lot of narcissism in self-hatred."/ It's such a simple statement, but that opened some kind of a lock in my mind a few years back when I first encountered it, because I had never made an association between the two!

That paradox has been present in my life as long as I can remember, as I've fluctuated from feeling absolutely horrid about myself, to standing on an iridescent cloud of my own self-importance, feeling like I have the potential to become anything. Only recently I've started finding balance in my life, and it came from a place of humility, not retribution. The problem never was the unjustness of the pain I've had to endure, but my knee-jerk reaction to it, which was /bitterness/, that I just let build up over the years. Depression is an understandable and a fully human reaction to trauma, but bitterness in my case was feeding into it, keeping the worst insecurities and distorted narratives alive.

And to think, I thought my suffering was somehow unique and exceptionally noble. /How gravely mistaken have I been!/

These days I find more strength in truthfulness and sincerity, than I've ever found in bitterness. It's been a long road, and I hope there's still a long one ahead.

Peace!
