#+TITLE:Tavastian wilderness and reflections
#+DATE:<2023-04-23>
#+KEYWORDS: life,philosophy,travel

Last week, I had the pleasure to visit the Tavastian heartland for four days, doing a somewhat more intensive trek than any of the ones I've been to so far. Me and my friend walked a total of around 43 kilometers, with about two-thirds of it with heavy backpacks on.

I was slightly worried about the endurance of my feet, as I just got new boots and didn't really have time to properly break them in, maybe having travelled around 30 kilometers in them before undertaking this trip, but they carried me gladly the whole trip.

Our plan was to embark on Ilvesreitti (lit. Lynx trail), which connects many of the Tavastian natural reserves, national parks and other places of interests, so one could theoretically trek more than 200 kilometers on this trail, although some of the connecting paths go alongside roads, quarries and industrial forests, so it's not really a continuous landscape route. At least it well underlines the fact how splintered and precious Finnish nature reserves are.

* Torronsuo and Ruostejärvi (First night)
We arrived at Eerikkilä Sport & Outdoor Resort at Ruostejärvi (lit. Rust lake) on the Wednesday afternoon of 12th of April, 2023. The resort was a noisy, unpleasant place, but luckily we didn't have to suffer the presence of loud-mouthed sports youth long, as Eerikkilä was just a staging ground for our first day of travel.

We left the resort northwestward, towards the Torronsuo national park, which is a large and deep swamp in the Tavastia Proper, Finland. The trail was in a bad shape at some places and we had to cross many flooding ditches where duckboards were completely submerged or rotten out of existence. An interesting phenomenon happened whenever we reached a more dense swamp basin, as it emanated colder air than anywhere else in the forest. It was springtime after all and most of the snow had already melted, but clearly through some odd landscape formation, the ground was in deep enough frost for it to affect the temperatures around it tremendously.

We slightly deviated from our planned path, as was eminent from the amount of water in ditches, the areas crossing the swamp proper could prove to be hard to cross, so we took a secondary route. In hindsight, the secondary route probably wasn't that much better, as most of the problematic ditches were on that stretch of trail. But nevertheless, we managed to reach the eastern extent of Torronsuo without too much trouble.

The Torronsuo proper was an awe-inspiring sight. The immense skies opened in front of us and we were greeted with birdsongs of all imaginable forms. We stopped to relax a bit, fix ourselves some supper and just listen the birds singing.

We wanted to get back to a shelter before dark, so we didn't stay for too long. The return trip back to Eerikkilä was somewhat uneventful - boring, but fairly easy terrain. The sun was just setting, when we reached our vehicle and moved it to the other side of the lake, to seek out a place to sleep.

On a hill on the southeastern coast of Ruostejärvi, there was a nice lean-to shelter, which we found luckily unoccupied. We put down our gear, chopped some firewood and stayed there for the night. It probably went below zero Celcius during the night and I did sleep a little restlessly, but all-in-all, it was a good night.

* Liesjärvi (Second night)
We woke up to the second day still slightly tired from yesterday's trek, but still feeling powerful and up to the task of exploring the Liesjärvi national park next. But first things come first - coffee. Nothing happens on the trail until there's a kettle boiling on a fire.

Once again, we gathered our gear and relocated to Liesjärvi with our vehicle. We could've walked there, but yesterday's realizations about Ilvesreitti made us a bit doubtful of the connecting road between Ruostejärvi and Liesjärvi. Looking at the map, it would've been similar sort of boring as the return trip from Torronsuo yesterday, so we opted for a solution that gave us more time and energy to explore the more interesting environs instead.

Upon reaching Liesjärvi, we decided to put down our backpacks for a while, fill our water supplies from a nearby well and visit the close-by Hyypiö trail, which ascends to the Hyypiökallio. (Hyypiö in Finnish vernacular describes a weird, creepy person, but the archaic meaning of Hyypiö is that of an eagle-owl, so the place is literally called the Owl Cliff)

It was my 35th birthday, so being welcomed by the view from the cliff's summit was more than I could've hoped for my anniversary of existing on this Earth. We spent a short moment on the summit, having a discussion about how it has clearly been a place of significance for a long time before us, looking at how the rock had become bare from who knows how many activities along the centuries.

It was already close to noon, so we descended down, picked up our backpacks and headed northwards to Siltalahti to light some fires, have lunch and another round of coffee. Our destination was to reach a kota next to the lake Kaksvetinen (lit. double waters) and stay there for the night, provided there was no-one there.

The trek to Kaksvetinen was an eventful one. We travelled through a swamp we dubbed the "magic forest". It was a severely flooding mixture of swamps and dense old forests, with large fallen trees left to rot in the ground, which provides an elaborate microecosystem for all sorts of life to thrive in. In contrast, we also travelled through a horrendous tree farm, with all the old trees cut down and replaced with saplings. Sure, it's efficient and all wood is of the same age when it gets chopped, but I absolutely detest this kind of systematic, industrialized destruction of the environment. There are of course alternative and objectively better, less harmful ways to doing this, but do the forest owners or woodcutters care about such things?

The trail was cut off at one point, but we decided to brave through it anyway, as there were fresh footprints in the icy slush on the trail anyway and the detour would've been a kilometer-and-a-half of extra travel and we were quite tired already at that point. The kota was empty, with a few smoking embers in the fire pit. Clearly whoever's footprints we observed earlier stopped by there as well. It was already becoming dark, so once again we set out to camp there, fixing ourselves some firewood, have some supper and rest until tomorrow.

* Liesjärvi (Third night)
It was a very cold morning on the third day. Kota protected us from the wind and it was quite a nice night overall, but getting up from the soft, warm confines of the sleeping bag was an exercise in willpower. We lit a small fire, prepared breakfast and started to clear out the camp.

Our first plan for the third day would be to return to the well to resupply our water, but through a different route, so we could see as much of the area as possible. Here we had the option of doing another ascension to a hill and descend back down, but reiterated on the idea since we knew there was a route around it, which would open us a view to the Liesjärvi lake itself. The route was a bit of a bore, simple rural road that was an easy travel, but again a fine tradeoff, as we'd conserve our strength for afternoon's more interesting trails. An ermine (or some close cousin thereof) greeted us on the way back to the well.

We crossed along the Kyynäränharju ridge to get to the southern shore. There was a small opening with a bridge, which acted as a funnel for the water, leaving it open and streaming. It was an interesting sight, as most of the lake was still covered in ice, sans the area around the bridge. We made our way towards Savilahti, a marked camping site, at which we were planning to spend the night. It was way too early for that though, so we hid our gear under a tarp in a spot shielded from any passerby's immediate gaze. So far, we hadn't come across any other travellers in the entire park, figuring it was safe enough to leave the backpacks there for a few hours.

Carrying only small packs, we continued southwards towards Korteniemi, a historic farmsite, where the forest ranger of Liesjärvi used to live with their family. We sat down for a while under an old apple tree, digging into some of the last of our rations and having a short rest before returning to the camp. Upon leaving the site, we came across the first other person in the entire park. Very calm and an unhurried place, this Liesjärvi.

We took a small detour and returned to Savilahti along a small rural road. As we were putting up our camp, a group of other campers arrived at Savilahti. They were a quiet bunch and didn't bother us the very least. We had a nice view of the sunset, before retiring to our separate accommodations.

I slept very pleasantly in my hammock, even if it was again a cold morning the next day. We'd make some coffee, pack our bags and start heading home after spending those three nights in the woods. I felt thoroughly transformed and content. Even having to wait at the train station or navigating through the masses of people at Tampere city center didn't dampen my spirits.

* The absolute significance of this trip

During our trip, we had plenty of fruitful discussions, of willpower, of Simone Weil, of transcendentalism, self-cultivation and asubjectivity. One of the most powerful realizations I had, was how I've been a slave to my mysticism, which I effectively have been using as means to escape.

I've even written before of how aesthetics are a big part of my mind "cheating" itself into finding meaning, but I came to the conclusion that I have not met the world on its terms. It's almost as if interfacing with reality through a proxy - a distorted, kaleidoscopic vision, that won't let us get ahold of the essence of things. It's easy to get lost in fantasies when in the woods, trying to force ourselves to some mystical experience through force of will, instead of letting go of control and letting ourselves to experience the events as-is, being simply mindful of the present and not trying to force meaning.

I think this asubjectivity is the difference between just being a tourist in the forest and of being an actual participant in the experience. We are not separate from nature, but a part of that whole. Instead of surrendering to the fantasy of being some heroic wanderer in some Tolkienesque fantasy, I now just try to breathe in and appreciate the things that are there, currently present, instead of letting myself become weary of reality, to dive in some kind of dissonant oughts-to.

I feel like this latest forest trip has had a profound effect on my thinking and especially in bringing some of it into practice. I've since taken a habit of doing long walks in the forests close-by to my home. There are plenty of trails there that I just simply ignored, thinking they couldn't match my sense of aesthetics. I've found absolutely breathtaking locations by simply taking long, winding paths. Maybe this is in a way some perverse forrestgumpian attempt to make sense into my own existence by simply existing out there instead of in my apartment.

Similarly, I've taken up a project of learning more about the American transcendentalists. Thoreau's ideas of simple living and seeking to elevate ones self to a higher level through careful cultivation and frequent visits to nature is something I found very intriguing.

We're already planning for the next trip in the summer. Hopefully this time between will be fruitful for integrating all these experiences and learning more about the world and the human condition.

Also, it's 23th of April, have a happy International Pallas Cat Day!
