#+TITLE: Site update
#+DATE: <2021-12-19>
#+KEYWORDS: tech,life

I updated the site a bit. I've been pretty busy and somehow the ramshackle state of this blog has slightly decreased my motivation to publish anything. I've written plenty of drafts, but somehow I needed to address a few things beforehand, especially now that Yule holidays are coming soon and I'd rather just write and publish things instead of tinkering around the website.

** Post tags

Posts are now tagged with keywords, and those keywords are shown in the post listings. I wrote a new function in /elisp/ that runs after creation of the post archive, which parses the keywords from the archive and creates filtered pages for specific tags. That's something I've been wanting to do for a while, but couldn't just find proper time to figure out. I'm pretty happy how that turned out, even if it's a bit /hackish/ solution.

** Gallery

It's rather confusing to profess myself being an artist, and then have no art on display whatsoever! This update rectifies that oversight, as now there's a new section for my more visual endeavours. The current works there are rather recent, but I think that's fine, as there's some emotional baggage with my older works from around 2016-2019, and I find them somewhat distasteful in my current, more developed mental state. Maybe some of that work will grow on me and I will include something from the past as well, but we'll see.

I updated the license information as well, since art is a bit more personal thing and I'm not entirely comfortable with licensing it to Creative Commons, so I'll retain the copyright for now. The text content on the site is still governed by CC-BY 4.0, so nothing has changed.

** Future plans

To be honest, I don't really know what is the next step! I'll probably do small tweaking with palettes and layouts, but right now I feel the site addresses all the needs I have at the moment.

In my rebellion against walled garden internet services, I'd like to have a separate section for things like book recommendations, just to decouple myself from Goodreads. Implementing RSS feeds for content would be an interesting thing to do as well.
