# Workflow for automatic site deploy
name: "Deploy site to GitHub Pages"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 28.2

    - name: Install Dart Sass
      run: sudo snap install dart-sass

    - name: Setup imagemagick
      run: |
        sudo apt-get update -y
        sudo apt-get install -y imagemagick

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build 'docs'
      run: make SASS=dart-sass

    - name: Deploy to 'gh-pages' branch
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: docs

